const assert = require('node:assert/strict');
const plan = require('../static/plan.js');
const journey = {steps:[{id:'a',checklist:['One','Two']},{id:'b',checklist:['Choice checked'],choices:[{id:'temporary'},{id:'transfer'}]},{id:'c',checklist:['Last']}]};
const checks={}, state={};
assert.equal(plan.frontier(journey,checks,state),0);
assert.equal(plan.confirm(journey,1,checks,state),false,'Cannot skip first step');
checks['a:0']=true;
assert.equal(plan.confirm(journey,0,checks,state),false,'Partial checklist cannot confirm');
checks['a:1']=true;
assert.equal(plan.frontier(journey,checks,state),0,'Checks alone do not unlock next step');
assert.equal(plan.confirm(journey,0,checks,state),true);
assert.equal(plan.frontier(journey,checks,state),1);
checks['b:0']=true;
assert.equal(plan.confirm(journey,1,checks,state),false,'Choice required');
state.choices={b:'made-up'};
assert.equal(plan.confirm(journey,1,checks,state),false,'Choice must match allowed values');
state.choices.b='temporary';
assert.equal(plan.confirm(journey,1,checks,state),true);
assert.equal(plan.confirm(journey,2,checks,state),false);
checks['c:0']=true;
assert.equal(plan.confirm(journey,2,checks,state),true);
assert.equal(plan.frontier(journey,checks,state),3,'Summary opens only after all confirmations');
const restored=JSON.parse(JSON.stringify(state));
assert.equal(plan.frontier(journey,checks,restored),3,'Confirmations survive storage round trip');
checks['a:0']=false; plan.reopen(journey,0,state);
assert.equal(plan.frontier(journey,checks,state),0);
assert.deepEqual(state.confirmed,{},'Changing an earlier check revokes all dependent confirmations');
console.log('PASS: sequential plan checks, choices, confirmation, persistence and invalidation');
