"""One guided case for each topic in the public YesMilano How To catalogue."""
from pathlib import Path
import json

CATALOG = json.loads((Path(__file__).parent / 'data/how-to-catalog.json').read_text())


def additional(b, step, base):
    def guide(id, title, subtitle, icon, tone, question, rows, scope=None):
        entry = next(c for c in CATALOG if c['id'] == id)
        steps = []
        for row in rows:
            sid, tit, ten, bit, ben, checks, *options = row
            opts = options[0] if options else {}
            steps.append(step(sid, (tit, ten), (bit, ben), opts.get('source', entry['indexed_url']), checks, opts.get('audiences')))
        return dict(id=id, title=b(*title), subtitle=b(*subtitle), icon=icon, tone=tone,
                    tag=b('GUIDA HOW TO', 'HOW TO GUIDE'), questions=[b(*question)],
                    steps=steps, plan_revision='howto-1', scope=b(*scope) if scope else None)

    non_eu = {'audiences':['non-eu']}
    temporary_audience = {'audiences':['italian','eu']}
    return [
        guide('visa', ('Il visto per studiare.', 'Get a student visa.'),
              ('Prima del viaggio: percorso, documenti e consolato.', 'Before travelling: route, documents and consulate.'), 'passport', 'blue',
              ('Come preparo la richiesta del visto per studio?', 'How do I prepare a study-visa application?'), [
                  ('route','Verifica quale percorso di ingresso ti riguarda','Check your entry route',
                   'La guida riguarda il visto per studenti non UE. Confronta cittadinanza, durata degli studi e situazione di ingresso con il consolato e l’università. Se sei italiano o cittadino UE, consulta i servizi competenti per i documenti pertinenti al tuo caso.',
                   'This guide covers study visas for non-EU students. Check citizenship, study duration and entry circumstances with your consulate and university. Italian or EU students should check the relevant services for their own document route.',
                   [('Ho verificato con la fonte a chi si rivolge questa guida','I checked who this guide is for')]),
                  ('prepare','Prepara il dossier con l’università','Prepare the file with your university',
                   'Consulta ammissione, preiscrizione e documenti richiesti nella guida e nelle istruzioni del consolato. Individua chi ti aiuta per un allegato mancante prima di prenotare.',
                   'Check admission, pre-enrolment and required documents in the guide and consulate instructions. Identify support for missing attachments before booking.',
                   [('Ho verificato la documentazione con università e consolato','I checked documents with the university and consulate'),('Ho preparato gli allegati pertinenti','I prepared the relevant attachments')],non_eu),
                  ('apply','Segui il canale del consolato','Follow the consulate channel',
                   'Verifica modalità di appuntamento, presentazione e tempi sul sito del consolato competente. Presenta la richiesta sul canale ufficiale e conserva i riferimenti per seguire la pratica.',
                   'Check appointments, submission and timing on the relevant consulate website. Apply through the official channel and keep details for following your application.',
                   [('Ho verificato il canale e i tempi applicabili','I checked the relevant channel and timing'),('Ho organizzato la presentazione della richiesta','I organised application submission')],non_eu)],
              ('Guida per studenti non UE · verifica il tuo caso', 'Non-EU student guide · check your circumstances')),
        guide('permit', ('Il permesso di soggiorno.', 'Get your residence permit.'),
              ('Kit, ricevuta e appuntamento in Questura.', 'Application kit, receipt and Police appointment.'), 'passport', 'rose',
              ('Quali passaggi servono per il permesso di soggiorno?', 'What are the residence-permit steps?'), [
                  ('route','Distingui visto e permesso','Distinguish visa from permit',
                   'Il visto e il permesso hanno funzioni diverse. La guida sul permesso riguarda gli studenti non UE: verifica con le autorità la procedura per il tuo titolo e la scadenza subito all’arrivo. Il piano non sospende i termini.',
                   'A visa and a residence permit serve different purposes. This guide covers non-EU students: check the route for your status and the deadline with the authorities as soon as you arrive. The plan does not suspend deadlines.',
                   [('Ho letto a chi si applica la procedura e quando verificare la scadenza','I checked who the process applies to and when to check the deadline')]),
                  ('kit','Prepara kit e allegati','Prepare the kit and attachments',
                   'Usa la checklist della guida e chiedi supporto a università o patronato. Verifica gli allegati per il tuo caso; non ritardare la richiesta solo perché manca il codice fiscale, che la guida indica come non obbligatorio nel kit.',
                   'Use the guide checklist and get help from your university or patronato. Check attachments for your case; do not delay solely because a tax code is missing, as the guide says it is not mandatory in the kit.',
                   [('Ho verificato il termine con il servizio competente','I checked the deadline with the relevant service'),('Ho preparato kit e allegati con il supporto corretto','I prepared the kit and attachments with appropriate support')],non_eu),
                  ('receipt','Consegna e conserva la ricevuta','Submit and keep the receipt',
                   'Individua un ufficio postale abilitato tramite la guida. Dopo la consegna conserva la ricevuta e verifica data, luogo e documenti indicati per la convocazione in Questura.',
                   'Find an enabled post office through the guide. After submission keep the receipt and check the date, location and required documents for the Police appointment.',
                   [('Ho consegnato la richiesta sul canale ufficiale','I submitted the application through the official channel'),('Ho conservato ricevuta e indicazioni per l’appuntamento','I kept the receipt and appointment instructions')],non_eu)],
              ('Guida per studenti non UE · verifica il tuo caso', 'Non-EU student guide · check your circumstances')),
        guide('taxcode', ('Il tuo codice fiscale.', 'Get your tax code.'),
              ('Dall’università al documento che ti serve.', 'From university support to the document you need.'), 'documents', 'lavender',
              ('L’università può aver già richiesto il mio codice fiscale?', 'Could my university already have requested my tax code?'), [
                  ('existing','Verifica se lo hai già','Check whether you already have it',
                   'Controlla i documenti che hai e chiedi all’università se il codice fiscale è già stato richiesto per te. Evita richieste duplicate e non inserire il codice in chat.',
                   'Check your documents and ask whether your university already requested a tax code for you. Avoid duplicate applications and do not enter the code in chat.',
                   [('Ho verificato se il codice è già disponibile','I checked whether the code is already available')]),
                  ('documents','Individua documenti e canale','Identify documents and the channel',
                   'Se devi richiederlo, segui la guida e le istruzioni dell’Agenzia delle Entrate per la tua situazione. Chiarisci con l’ufficio eventuali documenti mancanti.',
                   'If you need to apply, follow the guide and Revenue Agency instructions for your situation. Clarify missing documents with the office.',
                   [('Ho individuato il canale appropriato','I identified the appropriate channel'),('Ho verificato i documenti da preparare','I checked which documents to prepare')]),
                  ('request','Completa il passaggio necessario','Complete the required action',
                   'Presenta la richiesta sul canale ufficiale, oppure verifica il documento già ottenuto. Conserva il riferimento dell’ufficio per correggere eventuali incongruenze.',
                   'Apply through the official channel, or verify the document you already obtained. Keep the office contact for any discrepancies.',
                   [('Ho ottenuto o verificato il documento con il servizio competente','I obtained or verified the document with the relevant service')])]),
        guide('residence', ('La residenza a Milano.', 'Take residence in Milan.'),
              ('La procedura adatta al tuo arrivo e ai tuoi documenti.', 'The process for your arrival and documents.'), 'housing', 'sand',
              ('Quale canale uso per la residenza a Milano?', 'Which channel should I use for residence registration?'), [
                  ('route','Individua il tuo caso anagrafico','Identify your registration case',
                   'Distingui trasferimento da un altro Comune e primo arrivo dall’estero. Leggi la sezione della guida relativa alla tua situazione e confrontala con il servizio del Comune. Se stai valutando il domicilio temporaneo, esplora il relativo percorso prima di scegliere.',
                   'Distinguish moving from another municipality from first arrival from abroad. Read the relevant guide section and compare it with the City service. If considering temporary registration, explore that journey before choosing.',
                   [('Ho individuato la situazione pertinente','I identified the relevant situation')]),
                  ('documents','Prepara la documentazione pertinente','Prepare relevant documents',
                   'Verifica identità, documentazione abitativa e, quando pertinenti, titolo di soggiorno e altri allegati. Non usare requisiti di un profilo diverso dal tuo: chiarisci i dubbi con l’Anagrafe.',
                   'Check identity, housing evidence and, when relevant, residence-permit documents and other attachments. Do not apply another profile’s requirements to yourself; clarify questions with the Registry.',
                   [('Ho confrontato gli allegati con il mio caso','I checked attachments against my case'),('Ho chiarito eventuali documenti mancanti','I clarified missing documents')]),
                  ('access','Verifica accesso e modalità di richiesta','Check access and submission methods',
                   'Individua il servizio del Comune adatto al tuo caso e verifica credenziali o alternative di accesso. Non presumere di avere SPID o CIE se sei appena arrivato.',
                   'Identify the City service for your situation and check credentials or access alternatives. Do not assume you have SPID or CIE if you just arrived.',
                   [('Ho verificato il canale e come accedervi','I checked the channel and how to access it')]),
                  ('submit','Presenta e segui la richiesta','Submit and follow the application',
                   'Completa la richiesta sul servizio ufficiale e conserva ricevuta o protocollo. Verifica con l’ufficio come seguire la pratica e gli altri adempimenti relativi alla casa.',
                   'Complete the application on the official service and keep the receipt or reference. Ask the office how to follow the application and check other housing formalities.',
                   [('Ho gestito la richiesta sul canale ufficiale','I handled the application through the official channel'),('So dove seguire la pratica o chiedere assistenza','I know where to follow the application or ask for help')])]),
        guide('temporary', ('Un soggiorno temporaneo.', 'Get temporary residence.'),
              ('La guida UE e il caso degli studenti italiani fuorisede.', 'The EU guide and the Italian student-away-from-home case.'), 'housing', 'sage',
              ('Il domicilio temporaneo cambia la mia residenza?', 'Does temporary registration change my existing residence?'), [
                  ('route','Verifica il percorso temporaneo pertinente','Check the relevant temporary route',
                   'La guida YesMilano presenta la registrazione temporanea per cittadini UE. Per gli studenti italiani fuorisede consulta anche la FAQ del Comune sul domicilio temporaneo. Sono riferimenti da confrontare con l’Anagrafe, senza applicare automaticamente la procedura UE ai cittadini non UE.',
                   'YesMilano presents temporary registration for EU citizens. Italian students away from home should also consult the City FAQ on temporary domicile. Check the relevant route with the Registry; do not automatically apply the EU process to non-EU citizens.',
                   [('Ho verificato con la fonte a chi è rivolto il percorso','I checked who the route is for')]),
                  ('prepare','Prepara gli allegati della tua procedura','Prepare attachments for your procedure',
                   'Segui il modello e gli allegati indicati nella fonte pertinente. Per il domicilio degli studenti italiani usa la FAQ comunale, anziché copiare i requisiti della guida per studenti internazionali UE.',
                   'Follow the form and attachments in the relevant source. For Italian students’ temporary domicile use the City FAQ instead of copying the international EU-student requirements.',
                   [('Ho verificato modello e allegati per il mio caso','I checked the form and attachments for my case')],temporary_audience),
                  ('send','Controlla, firma e invia fuori dall’app','Review, sign and send outside the app',
                   'Controlla la dichiarazione e firma fuori dall’app. Usa il contatto della fonte ufficiale e conserva la risposta. Verifica durata dell’iscrizione e gestione della residenza d’origine con l’Anagrafe.',
                   'Review the declaration and sign outside the app. Use the official source contact and keep the response. Check registration duration and treatment of your existing residence with the Registry.',
                   [('Ho controllato e gestito la richiesta sul canale ufficiale','I checked and handled the request through the official channel'),('Ho conservato la risposta o il riferimento per seguirla','I kept the response or follow-up contact')],temporary_audience)],
              ('Guida UE · per i fuorisede italiani, verifica la FAQ del Comune', 'EU guide · Italian students should check the City FAQ')),
        guide('bank', ('Un conto per la vita qui.', 'Open a bank account.'),
              ('Costi, documenti e apertura sul canale della banca.', 'Costs, documents and opening through your bank.'), 'bank', 'blue',
              ('Quali documenti verifico prima di aprire un conto?', 'Which documents should I check before opening an account?'), [
                  ('compare','Confronta il conto che ti serve','Compare accounts for your needs',
                   'Parti dalla guida per orientarti. Confronta condizioni pubblicate, servizi necessari e costi con la banca; StudiaMI non sceglie un prodotto finanziario per te.',
                   'Start with the guide for orientation. Compare published terms, required services and costs with the bank; StudiaMI does not choose a financial product for you.',
                   [('Ho confrontato condizioni e servizi sul sito della banca','I compared terms and services on the bank website')]),
                  ('documents','Verifica i documenti con la banca','Check documents with the bank',
                   'Chiedi quali documenti sono richiesti per il tuo caso e se puoi completare l’apertura online o in filiale. Verifica se codice fiscale e documenti di soggiorno sono già disponibili; non caricarli qui.',
                   'Ask which documents are required for your circumstances and whether you can open online or in a branch. Check whether tax-code and immigration documents are available; do not upload them here.',
                   [('Ho verificato requisiti e canale direttamente con la banca','I checked requirements and the channel directly with the bank')]),
                  ('open','Gestisci l’apertura con la banca','Handle opening with the bank',
                   'Leggi le condizioni prima di firmare e completa l’operazione sul canale della banca. Conserva i riferimenti per assistenza, accesso e gestione del conto.',
                   'Read terms before signing and complete the operation through the bank. Keep contacts for support, access and account management.',
                   [('Ho gestito l’apertura sul canale della banca','I handled opening through the bank'),('So dove trovare condizioni e assistenza','I know where to find terms and support')])]),
        guide('phone', ('Il tuo numero italiano.', 'Get an Italian phone number.'),
              ('SIM, documenti e attivazione senza sorprese.', 'SIM, documents and activation with clarity.'), 'phone', 'peach',
              ('Come preparo l’attivazione di una SIM italiana?', 'How do I prepare to activate an Italian SIM?'), [
                  ('plan','Confronta offerta e condizioni','Compare plans and terms',
                   'Usa la guida per orientarti tra SIM e servizi. Confronta copertura, costi, rinnovo e condizioni aggiornate sul sito dell’operatore.',
                   'Use the guide to understand SIMs and services. Compare coverage, costs, renewal and current terms on the operator website.',
                   [('Ho verificato costi e condizioni con l’operatore','I checked costs and terms with the operator')]),
                  ('documents','Prepara i documenti richiesti','Prepare required documents',
                   'Verifica con l’operatore identità e altri documenti necessari nel tuo caso. Se ti serve un codice fiscale, usa il percorso dedicato; mantieni le scadenze urgenti dei documenti di soggiorno separate dall’attivazione della SIM.',
                   'Check identity and other required documents with the operator. If you need a tax code, use its journey; keep urgent immigration-document deadlines separate from SIM activation.',
                   [('Ho verificato documenti e canale di attivazione','I checked documents and the activation channel')]),
                  ('activate','Attiva e verifica il servizio','Activate and check the service',
                   'Completa l’attivazione sul canale dell’operatore. Controlla che il servizio funzioni e conserva i riferimenti per assistenza, rinnovo e gestione dell’offerta.',
                   'Complete activation through the operator. Check that the service works and keep support, renewal and plan-management contacts.',
                   [('Ho gestito l’attivazione con l’operatore','I handled activation with the operator'),('Ho verificato servizio e modalità di rinnovo','I checked the service and renewal process')])]),
        guide('support', ('Un aiuto tra gli uffici.', 'Use Patronato and CAF services.'),
              ('Trova il supporto per la pratica che ti blocca.', 'Find support for the application blocking you.'), 'citylife', 'sage',
              ('Per il mio dubbio serve un CAF o un patronato?', 'Should I contact a CAF or patronato for my question?'), [
                  ('service','Individua il servizio pertinente','Identify the relevant service',
                   'La guida distingue CAF e patronati. Parti dal tipo di problema e verifica chi offre assistenza per la tua pratica, senza presumere che tutti gli sportelli gestiscano tutto.',
                   'The guide distinguishes CAF and patronato services. Start with your issue and check who assists with your application; do not assume every desk handles everything.',
                   [('Ho individuato il servizio per il mio tipo di pratica','I identified the service for my application type')]),
                  ('prepare','Prepara le domande per il contatto','Prepare questions for the contact',
                   'Consulta contatti e modalità nella guida, poi verifica appuntamenti, eventuali costi e documenti con il servizio. In chat usa solo esempi inventati.',
                   'Consult guide contacts and access methods, then check appointments, any costs and documents with the service. Use invented examples only in chat.',
                   [('Ho verificato accesso e cosa preparare','I checked access and what to prepare'),('Ho preparato le domande sul blocco','I prepared questions about the blocker')]),
                  ('contact','Contatta e chiarisci il prossimo passo','Contact the service and clarify your next step',
                   'Contatta il servizio fuori dall’app. Conserva il riferimento e chiarisci quale documento o azione ti permette di riprendere la pratica.',
                   'Contact the service outside the app. Keep the contact and clarify which document or action lets you resume the application.',
                   [('Ho contattato il servizio o organizzato l’appuntamento','I contacted the service or arranged an appointment'),('Ho chiarito come riprendere la pratica','I clarified how to resume the application')])]),
        guide('identity', ('La carta d’identità italiana.', 'Get your Italian ID card.'),
              ('Requisiti, appuntamento e richiesta al Comune.', 'Requirements, appointment and City application.'), 'documents', 'lavender',
              ('Da dove comincio per richiedere la carta d’identità?', 'Where do I start to apply for an Italian ID card?'), [
                  ('requirements','Verifica i requisiti per il tuo caso','Check requirements for your case',
                   'Consulta la guida e le indicazioni del Comune. Distingui primo rilascio, rinnovo e documenti che hai già; se sei appena arrivato verifica prima la tua situazione anagrafica.',
                   'Consult the guide and City guidance. Distinguish first issuance, renewal and documents you already have; if newly arrived, check your registration situation first.',
                   [('Ho verificato il tipo di richiesta e i requisiti','I checked the application type and requirements')]),
                  ('appointment','Prepara documenti e appuntamento','Prepare documents and appointment',
                   'Verifica documenti, fotografie, canale di prenotazione e condizioni aggiornate sul servizio del Comune. Chiedi supporto se non riesci ad accedere.',
                   'Check documents, photos, booking channels and current conditions on the City service. Ask for help if you cannot access it.',
                   [('Ho verificato cosa preparare e come prenotare','I checked what to prepare and how to book')]),
                  ('request','Segui la richiesta e la consegna','Follow the application and delivery',
                   'Completa la richiesta presso il servizio competente. Conserva la ricevuta e verifica consegna e gestione dei codici ricevuti, fuori dalla chat.',
                   'Complete the application with the relevant service. Keep the receipt and check delivery and management of any codes outside chat.',
                   [('Ho gestito la richiesta sul servizio ufficiale','I handled the application through the official service'),('Ho verificato consegna e documentazione ricevuta','I checked delivery and received documentation')])]),
        guide('work', ('Lavorare mentre studi.', 'Work while studying.'),
              ('Condizioni, ricerca e supporto dell’università.', 'Conditions, job search and university support.'), 'work', 'sand',
              ('Cosa devo verificare prima di lavorare durante gli studi?', 'What should I check before working while studying?'), [
                  ('conditions','Verifica le condizioni applicabili','Check applicable conditions',
                   'Leggi la guida e verifica con l’ufficio competente le condizioni collegate al tuo titolo di soggiorno, se pertinenti. Non usare limiti o regole di un altro profilo e controlla le indicazioni aggiornate prima di accettare un lavoro.',
                   'Read the guide and check conditions related to your immigration status with the relevant office when applicable. Do not apply another profile’s rules; check current guidance before accepting work.',
                   [('Ho verificato le condizioni del mio caso con la fonte competente','I checked my conditions with the relevant source')]),
                  ('search','Individua i canali per la ricerca','Identify job-search channels',
                   'Parti dai riferimenti della guida e dal career service dell’università. Confronta attività, orari e compatibilità con gli studi; verifica chi pubblica l’offerta.',
                   'Start with the guide resources and your university career service. Compare duties, hours and study compatibility; verify who published the offer.',
                   [('Ho individuato canali verificabili e supporto universitario','I identified verifiable channels and university support')]),
                  ('offer','Chiarisci l’offerta prima di decidere','Clarify the offer before deciding',
                   'Chiedi chiarimenti su contratto, orari e documenti richiesti. Per dubbi sul lavoro o sul titolo di soggiorno contatta il servizio competente prima di firmare.',
                   'Clarify the contract, hours and required documents. Contact the relevant service about employment or immigration-status questions before signing.',
                   [('Ho chiarito le condizioni dell’offerta o il prossimo contatto utile','I clarified the offer terms or the next useful contact')])]),
        guide('language', ('Fai spazio all’italiano.', 'Learn Italian.'),
              ('Livello, risorse e iscrizione al corso.', 'Level, resources and course registration.'), 'language', 'peach',
              ('Come trovo un corso di italiano adatto al mio livello?', 'How do I find an Italian course for my level?'), [
                  ('goal','Scegli il tuo obiettivo linguistico','Choose your language goal',
                   'Italiano per la vita quotidiana, gli studi o gli sportelli? Parti dal tuo obiettivo e individua il livello da cui cominciare con il servizio del corso.',
                   'Italian for everyday life, study or service desks? Start with your goal and identify the starting level with the course provider.',
                   [('Ho definito l’obiettivo e verificato il livello di partenza','I defined my goal and checked my starting level')]),
                  ('course','Confronta le risorse della guida','Compare guide resources',
                   'Esplora le risorse proposte e verifica disponibilità, livelli, costi e modalità di partecipazione sui siti dei corsi. Le offerte possono cambiare.',
                   'Explore suggested resources and check availability, levels, costs and participation methods on course websites. Offers may change.',
                   [('Ho confrontato almeno una risorsa con le mie esigenze','I compared at least one resource with my needs')]),
                  ('join','Contatta il corso e organizza la partecipazione','Contact the course and plan participation',
                   'Segui il canale del corso per chiedere chiarimenti o iscriverti. Conserva orari, modalità di accesso e contatto per supporto.',
                   'Follow the course channel to ask questions or register. Keep the schedule, access instructions and support contact.',
                   [('Ho contattato il corso o organizzato l’iscrizione','I contacted the course or organised registration'),('Ho verificato quando e come partecipare','I checked when and how to participate')])]),
    ]
