"""Persona-based plans: source-backed orientation and explicit student confirmation."""
BASE = 'https://studyandwork.yesmilano.it/en'
CRM = 'https://servizicrm.comune.milano.it/centro-supporto'
DOMICILE = CRM + '/KA-00595/Domicilio-temporaneo-per-studenti-e-lavoratori'
VALID_PERMIT = CRM + '/KA-00598/Documenti-per-residenza-con-permesso-di-soggiorno-valido'
LEASE = CRM + '/KA-00329/Residenza-stranieri-in-affitto-documenti-immobile'
ITALIAN_RESIDENCE = CRM + '/KA-00371/Cambio-residenza-per-italiani-gia-in-Italia'
TARI = 'https://www.comune.milano.it/servizi/tributi/tari-dichiarazione-di-occupazione-di-appartamenti-e-immobili'
TARI_OCCUPANTS = CRM + '/KA-01960/'
PERSONA_GUIDES = [DOMICILE, VALID_PERMIT, LEASE, ITALIAN_RESIDENCE, TARI_OCCUPANTS]


def b(it, en):
    return {'it': it, 'en': en}


def s(id, title, body, source, checklist, owner, validation, **extra):
    return dict(id=id, title=b(*title), body=b(*body), source=source,
                checklist=[b(*c) for c in checklist], owner=b(*owner),
                validation=b(*validation), audiences=None, **extra)


def arrival_for(citizenship):
    if citizenship not in {'italian', 'non-eu'}:
        return None
    if citizenship == 'italian':
        steps = [
            s('giulia-study', ('Prima di decidere: borsa e ISEE', 'Before deciding: grants and ISEE'),
              ('Come Giulia, hai già codice fiscale, CIE e SPID. Il primo dubbio è se cambiare residenza possa incidere sulla borsa. Chiedi all’ufficio per il diritto allo studio quali condizioni valgono per il tuo bando: il Comune e l’assistente non possono determinarle.',
               'Like Giulia, you already have a tax code, CIE and SPID. Your first concern is whether changing residence affects a grant. Ask your university’s student-aid office about your specific call: the City and assistant cannot determine its conditions.'), BASE + '/study/how-to/scolarships-and-study-grants',
              [('Ho individuato l’ufficio per il diritto allo studio', 'I identified the student-aid office'), ('Ho chiarito con l’ufficio i dubbi sul mio bando prima di scegliere', 'I clarified my grant questions with that office before choosing')],
              ('Università · diritto allo studio', 'University · student aid'), ('Confermo di aver chiarito i vincoli del mio bando.', 'I confirm I clarified the conditions of my grant.')),
            s('giulia-status', ('Domicilio o residenza? Scegli il tuo piano', 'Temporary domicile or residence? Choose your plan'),
              ('Confronta tre possibilità da verificare rispetto alla tua situazione: restare iscritta nel Comune d’origine, chiedere il domicilio temporaneo per studenti, oppure trasferire la residenza. Il domicilio temporaneo dura un anno, mantiene la residenza d’origine e non si richiede se sei già residente a Milano. Non è equivalente al cambio di residenza.',
               'Compare three options against your circumstances: remain registered in your home municipality, request temporary student domicile, or transfer residence. Temporary domicile lasts one year, keeps your existing residence and cannot be requested if you already reside in Milan. It is different from transferring residence.'), DOMICILE,
              [('Ho confrontato le opzioni con le fonti e chiarito i dubbi con il Comune', 'I compared the options with the sources and clarified questions with the City')],
              ('Comune · Anagrafe', 'City · Registry'), ('Confermo la scelta per il mio piano; posso rivederla.', 'I confirm my plan choice; I can review it.'),
              choices=[{'id':'keep', 'title':b('Mantengo la residenza d’origine', 'Keep my current residence'), 'body':b('Verifico con il Comune che questa scelta sia adatta alla mia situazione temporanea.', 'Check with the City that this fits my temporary circumstances.')},
                       {'id':'temporary', 'title':b('Chiedo il domicilio temporaneo', 'Request temporary student domicile'), 'body':b('Preparo dichiarazione firmata e documento; invio io la richiesta.', 'Prepare a signed declaration and ID; send the request myself.')},
                       {'id':'transfer', 'title':b('Trasferisco la residenza', 'Transfer my residence'), 'body':b('Seguo il canale del Comune e verifico il termine di 20 giorni dal trasferimento.', 'Follow the City channel and check the 20-day deadline from moving.')}],
              extra_sources=[{'url':ITALIAN_RESIDENCE,'title':b('Cambio di residenza per cittadini italiani', 'Residence transfer for Italian citizens')}]),
            s('giulia-action', ('Dalla scelta alla prossima azione', 'Turn your choice into an action'),
              ('Riprendi la scelta appena confermata. Per il domicilio temporaneo prepara una dichiarazione firmata con dati anagrafici, indirizzo a Milano e Comune di residenza, e allega un documento. Per trasferire la residenza segui il servizio del Comune. Completa e invia tutto fuori da StudiaMI; non caricare documenti qui.',
               'Follow the choice you just confirmed. For temporary domicile, prepare a signed declaration with identity details, your Milan address and residence municipality, plus an ID. For a residence transfer, follow the City service. Complete and send everything outside StudiaMI; do not upload documents here.'), DOMICILE,
              [('Ho verificato i documenti e il canale per la scelta fatta', 'I checked documents and the channel for my choice'), ('Ho completato l’azione prevista, oppure confermato con il Comune che non devo presentare una richiesta', 'I completed the action, or confirmed with the City that no application is needed')],
              ('Comune · Anagrafe', 'City · Registry'), ('Confermo di aver gestito la mia scelta sul canale corretto.', 'I confirm I handled my choice through the correct channel.'),
              follows_choice='giulia-status', extra_sources=[{'url':ITALIAN_RESIDENCE,'title':b('Servizio per il cambio di residenza', 'Residence-transfer service')}]),
            s('giulia-home', ('La stanza: chiarisci contratto e TARI', 'Your room: clarify the contract and TARI'),
              ('Hai una stanza con un contratto per studenti. Controlla chi gestisce la TARI e cosa è già stato dichiarato per l’abitazione: una clausola sui pagamenti non chiarisce da sola chi deve fare la dichiarazione. Chiedi al titolare dell’utenza e al servizio tributi.',
               'You have a room with a student contract. Check who handles TARI and what has already been declared for the home: a payment clause alone does not establish who must submit a declaration. Ask the account holder and the tax service.'), TARI,
              [('Ho chiarito chi è il titolare dell’utenza TARI', 'I clarified who holds the TARI account'), ('Ho verificato la situazione già dichiarata per la casa', 'I checked what has already been declared for the home')],
              ('Comune · Tributi / referente della casa', 'City · Tax service / housing contact'), ('Confermo che responsabilità e situazione abitativa sono chiare.', 'I confirm responsibilities and the housing situation are clear.')),
            s('giulia-tari', ('TARI: verifica residenza e occupanti', 'TARI: check residence and occupants'),
              ('Se mantieni la residenza altrove, verifica la dichiarazione di variazione degli occupanti non residenti. La nuova occupazione e la variazione degli occupanti sono procedure diverse: individua con il servizio tributi quella pertinente prima di presentare una dichiarazione.',
               'If you keep residence elsewhere, check the declaration for changes to non-resident occupants. New occupancy and changes to occupants are different procedures: identify the applicable one with the tax service before submitting.'), TARI_OCCUPANTS,
              [('Ho verificato quale dichiarazione riguarda il mio caso', 'I checked which declaration applies'), ('Ho completato il passaggio richiesto o verificato che è già gestito dal titolare', 'I completed the required action or verified the account holder already handled it')],
              ('Comune · Tributi', 'City · Tax service'), ('Confermo di aver verificato l’adempimento TARI con il servizio competente.', 'I confirm I checked the TARI action with the relevant service.')),
            s('giulia-health', ('Il medico è a Lecce: trova il riferimento a Milano', 'Your doctor is back home: find your Milan contact'),
              ('Non aspettare di avere bisogno di assistenza. Individua ATS/ASST o il servizio sanitario competente e chiedi come accedere mentre studi fuori sede. Le condizioni del medico temporaneo dipendono dal servizio sanitario: StudiaMI non decide la tua copertura.',
               'Do not wait until you need care. Identify the relevant ATS/ASST or health service and ask how to access care while studying away from home. Temporary-doctor conditions belong to the health service; StudiaMI does not decide your coverage.'), HEALTH_URL,
              [('Ho individuato il servizio sanitario competente', 'I identified the relevant health service'), ('Ho verificato con il servizio come accedere all’assistenza nel mio caso', 'I checked with the service how to access care in my situation')],
              ('ATS / ASST · assistenza sanitaria', 'ATS / ASST · healthcare'), ('Confermo di sapere chi contattare e come accedere all’assistenza.', 'I confirm I know who to contact and how to access care.')),
        ]
        action = next(step for step in steps if step['id'] == 'giulia-action')
        action['routes'] = {
            'keep': {'source': ITALIAN_RESIDENCE, 'body': b(
                'Hai scelto di mantenere la residenza d’origine. Verifica con l’Anagrafe che questa scelta sia coerente con la tua situazione temporanea; non trattarla come un’esenzione generale dagli adempimenti. Conserva il riferimento dell’ufficio e le indicazioni ricevute. Non devi inviare una richiesta di domicilio temporaneo solo per completare il piano.',
                'You chose to keep your existing residence. Check with the Registry that this fits your temporary circumstances; do not treat it as a general exemption from formalities. Keep the office contact and its guidance. You do not need to send a temporary-domicile request just to finish this plan.')},
            'temporary': {'source': DOMICILE, 'body': b(
                'Hai scelto il domicilio temporaneo. La FAQ del Comune indica una dichiarazione firmata con dati anagrafici, indirizzo a Milano e Comune di residenza, più un documento di identità, da inviare via email al riferimento indicato nella fonte. Puoi preparare una bozza con segnaposti qui sotto: verifica e firma fuori dall’app, poi invia tu e conserva la risposta. Non caricare dati o documenti qui.',
                'You chose temporary student domicile. The City FAQ lists a signed declaration with identity details, Milan address and residence municipality, plus ID, to email to the contact in the source. Prepare a placeholder draft below: check and sign outside the app, send it yourself and keep the response. Do not upload data or documents here.')},
            'transfer': {'source': ITALIAN_RESIDENCE, 'body': b(
                'Hai scelto di trasferire la residenza. La FAQ del Comune indica ANPR e il termine di 20 giorni dal trasferimento. Verifica documenti e condizioni del tuo caso sul servizio ufficiale; usa lì SPID o CIE. Conserva il riepilogo della richiesta e verifica anche gli adempimenti TARI. StudiaMI non accede alla tua pratica e non la presenta.',
                'You chose to transfer residence. The City FAQ lists ANPR and a 20-day deadline from moving. Check documents and conditions on the official service; use SPID or CIE there. Keep the application summary and check TARI formalities too. StudiaMI neither accesses nor submits your application.')},
        }
        return dict(persona='Giulia', plan_revision='giulia-1',
                    subtitle=b('Da fuorisede a Milano: una scelta alla volta, senza dubbi lasciati indietro.', 'Student life away from home: one confirmed choice at a time.'),
                    plan_intro=b('Il piano di Giulia: chiarire borsa e residenza, rendere visibile l’arrivo, gestire casa, TARI e accesso ai servizi.', 'Giulia’s plan: clarify grants and residence, make arrival visible, manage housing, TARI and service access.'),
                    priority=b('Le scadenze del Comune valgono anche mentre il piano è bloccato. Se un dubbio resta aperto, contatta il servizio competente.', 'City deadlines still apply while a step is locked. Contact the relevant service if a question remains unresolved.'), steps=steps)
    steps = [
        s('visa', ('Passaporto e visto: parti dai documenti che hai', 'Passport and visa: start with what you have'),
          ('Come Reza, arrivi per una magistrale di due anni con visto per studio. Verifica con l’università e il consolato che il percorso di ingresso sia quello del tuo caso; raccogli i riferimenti per l’assistenza. Il visto di ingresso e il permesso di soggiorno sono documenti diversi.', 'Like Reza, you arrive for a two-year master’s with a study visa. Check your entry route with the university and consulate and identify support contacts. An entry visa and a residence permit are different documents.'), BASE + '/study/how-to/student-visa',
          [('Ho verificato passaporto, visto e indicazioni per il mio ingresso', 'I checked passport, visa and entry guidance'), ('Ho individuato il referente dell’università per studenti internazionali', 'I identified my university’s international-student contact')], ('Stato · Consolato / Università', 'State · Consulate / University'), ('Confermo il mio punto di partenza e il referente per i dubbi.', 'I confirm my starting point and support contact.')),
        s('permit', ('Priorità: prepara il kit del permesso', 'Priority: prepare the residence-permit kit'),
          ('La guida indica la richiesta entro 8 giorni lavorativi dall’arrivo. Verifica subito il termine con l’autorità competente, prepara il kit con università o patronato e controlla copertura sanitaria e allegati. Non aspettare il codice fiscale: la guida chiarisce che non è obbligatorio inserirlo nel kit.', 'The guide states application within 8 working days of arrival. Check the deadline immediately with the relevant authority, prepare the kit with your university or patronato and check health coverage and attachments. Do not wait for a tax code: the guide says it is not mandatory in the kit.'), PERMIT_URL,
          [('Ho verificato la scadenza senza attendere i passaggi successivi', 'I checked the deadline without waiting for later steps'), ('Ho preparato kit e allegati con il supporto competente', 'I prepared the kit and attachments with qualified support')], ('Stato · Questura / Poste / Università', 'State · Police / Post Office / University'), ('Confermo che il kit è pronto e conosco il termine da rispettare.', 'I confirm the kit is ready and I know the deadline.')),
        s('receipt', ('Consegna e ricevuta: conserva la prova', 'Submission and receipt: keep the proof'),
          ('Individua un ufficio postale abilitato nella guida. Dopo la consegna conserva ricevuta e convocazione per la Questura; controlla luogo, data e documenti dell’appuntamento. L’app non invia il kit e non verifica il tuo status di soggiorno.', 'Find an enabled post office through the guide. After submission keep your receipt and Police appointment letter; check location, date and appointment documents. The app does not submit the kit or verify immigration status.'), PERMIT_URL,
          [('Ho consegnato il kit sul canale ufficiale e conservato la ricevuta', 'I submitted the kit officially and kept the receipt'), ('Ho verificato la convocazione e cosa preparare per l’appuntamento', 'I checked the appointment letter and what to prepare')], ('Poste / Questura', 'Post Office / Police'), ('Confermo di avere ricevuta e indicazioni per l’appuntamento.', 'I confirm I have the receipt and appointment instructions.')),
        s('tax', ('Codice fiscale: verifica se l’università lo ha già richiesto', 'Tax code: check whether your university already requested it'),
          ('Chiedi all’università se dispone di una convenzione e ha già richiesto il codice fiscale. Se manca, segui la guida dell’Agenzia delle Entrate. Chiarisci quali servizi lo richiedono prima di aprire conto, SIM o altre pratiche; non inserirlo in chat.', 'Ask whether your university has an agreement and already requested your tax code. If missing, follow the Revenue Agency guide. Check which services require it before opening a bank account, SIM or other applications; do not enter it in chat.'), BASE + '/study/how-to/get-italian-tax-code-codice-fiscale',
          [('Ho verificato con l’università se il codice è già disponibile', 'I checked whether the university already has the code'), ('Ho ottenuto il codice o individuato con l’ufficio competente come risolvere il blocco', 'I obtained the code or identified with the relevant office how to resolve the blocker')], ('Agenzia delle Entrate / Università', 'Revenue Agency / University'), ('Confermo di aver gestito il passaggio sul codice fiscale.', 'I confirm I handled the tax-code step.')),
        s('reza-home', ('La stanza a Dergano: prepara le prove abitative', 'Your room in Dergano: prepare housing evidence'),
          ('Per la residenza in affitto il Comune indica la copia del contratto e l’eventuale ricevuta di registrazione. Chiedi i documenti al referente della casa e controlla come la tua sistemazione è documentata. Non cercare un documento presso un ufficio che non lo rilascia.', 'For residence registration as a tenant, the City lists a copy of the lease and any registration receipt. Ask your housing contact and check how your accommodation is documented. Do not ask an office for a document it does not issue.'), LEASE,
          [('Ho raccolto la documentazione abitativa pertinente', 'I collected the relevant housing documents'), ('Ho individuato chi chiarisce eventuali documenti mancanti', 'I identified who can clarify missing documents')], ('Referente della casa / Comune · Anagrafe', 'Housing contact / City Registry'), ('Confermo di aver verificato le prove della mia sistemazione.', 'I confirm I checked evidence of my accommodation.')),
        s('reza-residence', ('Residenza: scegli la procedura per il titolo che hai', 'Residence registration: match the process to your permit'),
          ('Permesso valido e attesa del primo rilascio non sono lo stesso caso: chiedi al Comune quale canale si applica. Con permesso valido, verifica passaporto, titolo di soggiorno e codice fiscale. Gli atti tradotti e legalizzati su famiglia e stato civile non sono obbligatori per l’iscrizione in sé: servono per registrare i rapporti di parentela e certificarli.', 'A valid permit and waiting for first issuance are different cases: ask the City which route applies. With a valid permit, check passport, permit and tax code. Translated and legalised family/civil-status records are not mandatory for registration itself; they are needed to record and certify family relationships.'), VALID_PERMIT,
          [('Ho chiarito con il Comune il canale adatto al mio titolo attuale', 'I clarified with the City the route for my current permit situation'), ('Ho verificato documenti e modalità di accesso senza presumere di avere SPID', 'I checked documents and access without assuming I have SPID')], ('Comune · Anagrafe', 'City · Registry'), ('Confermo di conoscere il percorso residenza applicabile e i documenti pertinenti.', 'I confirm I know the relevant residence route and documents.')),
        s('reza-tari', ('Casa e TARI: verifica la dichiarazione', 'Housing and TARI: check the declaration'),
          ('Verifica nuova occupazione, titolare dell’utenza e dichiarazioni già presenti con il servizio tributi. La TARI ha un proprio canale: non attendere il completamento della residenza per chiedere quale termine e adempimento valgono per la tua sistemazione.', 'Check new occupancy, the account holder and existing declarations with the tax service. TARI has its own channel: do not wait for residence registration to ask which deadline and action apply to your accommodation.'), TARI,
          [('Ho verificato titolare, dichiarazione pertinente e termine con il servizio tributi', 'I checked the account holder, applicable declaration and deadline with the tax service'), ('Ho gestito l’adempimento richiesto o verificato chi lo ha già completato', 'I handled the required action or verified who already completed it')], ('Comune · Tributi', 'City · Tax service'), ('Confermo di aver gestito o chiarito la dichiarazione TARI.', 'I confirm I handled or clarified the TARI declaration.')),
        s('reza-services', ('Salute e sportelli: sai a chi rivolgerti', 'Healthcare and service desks: know who to ask'),
          ('Individua il servizio sanitario competente per la copertura e l’accesso alle cure, e lo Student Desk per gli ostacoli tra enti. Chiedi al Comune come accedere se non hai SPID o CIE. Puoi chiedere spiegazioni in farsi alla chat; l’interfaccia resta disponibile in italiano e inglese.', 'Identify the relevant health service for coverage and care access, and the Student Desk for barriers between offices. Ask the City about access if you have no SPID or CIE. You can request explanations in Farsi in chat; the interface is available in Italian and English.'), BASE + '/international-student-desk',
          [('Ho individuato i riferimenti per salute e assistenza sui documenti', 'I identified healthcare and document-support contacts'), ('So quale ufficio contattare per un blocco di accesso o di lingua', 'I know which office to contact for access or language barriers')], ('ATS / ASST · Comune · Student Desk', 'ATS / ASST · City · Student Desk'), ('Confermo di avere un riferimento per i passaggi ancora aperti.', 'I confirm I have a support contact for any remaining issues.')),
    ]
    return dict(persona='Reza', plan_revision='reza-1', steps=steps,
                subtitle=b('Documenti, enti e scadenze: il piano per uno studente non UE.', 'Documents, offices and deadlines: a plan for a non-EU student.'),
                plan_intro=b('Il piano di Reza: rompere il giro tra uffici, preparare ogni documento con il referente giusto e confermare un passaggio alla volta.', 'Reza’s plan: break the loop between offices, prepare documents with the right contact and confirm one step at a time.'),
                priority=b('Priorità immediata: verifica il termine del permesso (8 giorni lavorativi). TARI e copertura sanitaria vanno verificate anche in parallelo: il blocco dell’app non sospende le scadenze.', 'Immediate priority: check the permit deadline (8 working days). Check TARI and health coverage in parallel too; app locks do not suspend deadlines.'))


HEALTH_URL = BASE + '/study/how-to/national-health-service-students-step-step'
PERMIT_URL = BASE + '/study/how-to/residence-permit-students'
